module.exports = {
  // User requests
  REQ_USER_LOGIN: 'REQ_USER_LOGIN',
  REQ_SESSION_LOGIN: 'REQ_SESSION_LOGIN',
  REQ_CURRENT_GAME: 'REQ_CURRENT_GAME',
  REQ_SWEEP: 'REQ_SWEEP',
  REQ_FLAG: 'REQ_FLAG',
  REQ_CLOSE: 'REQ_CLOSE',
  REQ_LOGOUT: 'REQ_LOGOUT',

  // Server responses
  SEND_USER: 'SEND_USER',
  SEND_CURRENT_GAME: 'SEND_CURRENT_GAME',
  SEND_SWEEP_RESULT: 'SEND_SWEEP_RESULT',
  SEND_FLAG_RESULT: 'SEND_FLAG_RESULT',
  SEND_GAME_STATS: 'SEND_GAME_STATS',
  SEND_ERROR: 'SEND_ERROR',
};
